name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  wasm_build:
    uses: ./.github/workflows/wasm-build.yml
    with:
      build_type: ${{ github.event_name == 'pull_request' && 'Debug' || 'Release' }}

  web_frontend:
    needs: wasm_build
    uses: ./.github/workflows/web-frontend.yml
    with:
      build_type: ${{ github.event_name == 'pull_request' && 'Debug' || 'Release' }}
